#!/usr/bin/env python3
"""Regenerates src/services/oni-save/element-phases.ts from the game's own
element definitions.

The game ships its element table as plain YAML under
StreamingAssets/elements/, one file per phase, and every entry declares its
`state`. That is the only place the phase is written down in a form this
project can read - the parser's SimHashes enum carries names and hashes and
nothing else.

The editor needs it to say what a pile of something actually is. Loose solid
lies around in clumps, loose liquid in bottles and loose gas in canisters, and
calling all three "clumps" - which the page did - is wrong for every liquid in
a colony.

    python extract-element-phases.py "C:/Steam/steamapps/common/OxygenNotIncluded"

No decompiler needed; this is a text file the game installs.
"""

import re
import sys
from pathlib import Path

# The four files, and the phase each one is expected to declare. Reading the
# declared `state` rather than trusting the filename means a mismatch is a
# loud failure instead of a silent miscategorisation.
FILES = {
    "solid.yaml": "Solid",
    "liquid.yaml": "Liquid",
    "gas.yaml": "Gas",
    "special.yaml": "Vacuum",
}

PHASE_BY_STATE = {
    "Solid": "solid",
    "Liquid": "liquid",
    "Gas": "gas",
    "Vacuum": "vacuum",
}

OUT = Path(__file__).resolve().parent.parent / "src/services/oni-save/element-phases.ts"

HEADER = """// Generated by tools/extract-element-phases.py from the game's own
// StreamingAssets/elements/*.yaml. Do not edit by hand.
//
// The phase decides what a loose pile of an element is called: solids lie
// around in clumps, liquids in bottles and gases in canisters.

export type ElementPhase = "solid" | "liquid" | "gas" | "vacuum";

export const ELEMENT_PHASES: Record<string, ElementPhase> = {
"""

FOOTER = """};
"""


def parse(path: Path, expected_state: str) -> list[tuple[str, str]]:
    """Pulls (elementId, state) out of one file, in declaration order."""
    entries: list[tuple[str, str]] = []
    element_id: str | None = None

    for line in path.read_text(encoding="utf-8").splitlines():
        # `elementId: Aerogel`, sometimes with a trailing comment.
        match = re.match(r"\s*-?\s*elementId:\s*([A-Za-z0-9_]+)", line)
        if match:
            element_id = match.group(1)
            continue

        match = re.match(r"\s*state:\s*([A-Za-z]+)", line)
        if match and element_id is not None:
            state = match.group(1)
            if state != expected_state:
                raise SystemExit(
                    f"{path.name}: {element_id} declares state {state}, "
                    f"but this file should hold {expected_state} only"
                )
            entries.append((element_id, state))
            element_id = None

    return entries


def main() -> None:
    if len(sys.argv) != 2:
        raise SystemExit(f"usage: {sys.argv[0]} <path to OxygenNotIncluded>")

    elements_dir = Path(sys.argv[1]) / "OxygenNotIncluded_Data/StreamingAssets/elements"
    if not elements_dir.is_dir():
        raise SystemExit(f"no elements directory at {elements_dir}")

    rows: list[tuple[str, str]] = []
    for filename, expected_state in FILES.items():
        path = elements_dir / filename
        if not path.is_file():
            raise SystemExit(f"missing {path}")
        found = parse(path, expected_state)
        print(f"{filename}: {len(found)} elements")
        rows.extend(found)

    seen: dict[str, str] = {}
    for element_id, state in rows:
        if element_id in seen and seen[element_id] != state:
            raise SystemExit(f"{element_id} appears twice with different states")
        seen[element_id] = state

    body = "".join(
        f'  {element_id}: "{PHASE_BY_STATE[state]}",\n' for element_id, state in rows
    )
    OUT.write_text(HEADER + body + FOOTER, encoding="utf-8")
    print(f"wrote {len(rows)} elements to {OUT}")


if __name__ == "__main__":
    main()
