#!/usr/bin/env python3
"""Regenerates src/services/oni-save/food-calories.ts from the game's own food
tuning.

Food is the one material whose quantity the game does not show in the unit the
save stores. A save records `PrimaryElement.Units`; the game shows kilocalories,
and the number between them - calories per unit - lives only in the assembly, as
`TUNING.FOOD.FOOD_TYPES`: 75 fields, each one `new EdiblesManager.FoodInfo(id,
caloriesPerUnit, ...)`.

`GameUtil.GetFormattedCalories` divides by 1000 and appends kcal, so seven
Ovagro Figs at 325000 calories each read as 2,275 kcal.

Needs a decompiled copy of the game, the same one extract-trait-effects.py
uses:

    ilspycmd -p -o decomp ".../Managed/Assembly-CSharp.dll"
    python extract-food-calories.py     # expects ./decomp alongside it

Two things in the table are not plain numbers, and both are resolved rather
than guessed:

  * nine ids are written `SomeConfig.ID` instead of a literal, and are read out
    of that config class;
  * one entry (Pemmican) computes its calories from another entry's.

Anything it cannot resolve is reported and the file is not written.
"""

import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
DECOMP = HERE / "decomp"
OUT = HERE.parent / "src/services/oni-save/food-calories.ts"

HEADER = """// Generated by tools/extract-food-calories.py from TUNING.FOOD.FOOD_TYPES in
// the game's assembly. Do not edit by hand.
//
// Calories per unit of food. A save stores `PrimaryElement.Units`; multiply by
// the value here and divide by 1000 for the kilocalories the game shows.

export const FOOD_CALORIES_PER_UNIT: Record<string, number> = {
"""

FOOTER = """};
"""

# `public static readonly EdiblesManager.FoodInfo NAME = new
#  EdiblesManager.FoodInfo(<id>, <calories>, ...`
ENTRY = re.compile(
    r"FoodInfo\s+(?P<field>[A-Z0-9_]+)\s*=\s*new\s+EdiblesManager\.FoodInfo\(\s*"
    r"(?P<id>\"[^\"]+\"|[A-Za-z0-9_]+\.ID)\s*,\s*"
    r"(?P<calories>[^,]+),"
)

CONFIG_ID = re.compile(
    r"public\s+(?:const|static(?:\s+readonly)?)\s+string\s+ID\s*=\s*\"([^\"]+)\""
)


def find_file(stem: str) -> Path:
    """Locates a decompiled class by file name, wherever ilspycmd filed it."""
    matches = list(DECOMP.rglob(f"{stem}.cs"))
    if not matches:
        raise SystemExit(f"no {stem}.cs under {DECOMP} - was the decompile complete?")
    return matches[0]


def resolve_config_id(reference: str) -> str:
    """`CarrotConfig.ID` -> the string that class declares."""
    class_name = reference.split(".")[0]
    text = find_file(class_name).read_text(encoding="utf-8")
    match = CONFIG_ID.search(text)
    if not match:
        raise SystemExit(f"{class_name} has no string ID field")
    return match.group(1)


def resolve_calories(expression: str, resolved: dict[str, float]) -> float:
    """A float literal, or arithmetic over entries already read.

    Only the two shapes the table actually uses are accepted. Anything else is
    an error rather than a guess, because a silently wrong calorie count looks
    exactly like a right one.
    """
    expression = expression.strip()

    # `HARDSKINBERRY.CaloriesPerUnit` -> the value read for that field.
    def substitute(match: re.Match[str]) -> str:
        field = match.group(1)
        if field not in resolved:
            raise SystemExit(
                f"{field}.CaloriesPerUnit is used before it is defined - "
                "the table's declaration order changed"
            )
        return repr(resolved[field])

    expression = re.sub(r"([A-Z0-9_]+)\.CaloriesPerUnit", substitute, expression)
    # C# float suffixes.
    expression = re.sub(r"(\d)[fF]\b", r"\1", expression)

    if not re.fullmatch(r"[0-9eE_.+\-*/() ]+", expression):
        raise SystemExit(f"cannot resolve calories from: {expression!r}")

    return float(eval(expression))  # noqa: S307 - guarded by the pattern above


def main() -> None:
    if not DECOMP.is_dir():
        raise SystemExit(
            f"no decompiled source at {DECOMP}\n"
            "run: ilspycmd -p -o decomp '.../Managed/Assembly-CSharp.dll'"
        )

    text = find_file("FOOD").read_text(encoding="utf-8")

    resolved: dict[str, float] = {}
    rows: list[tuple[str, float]] = []

    for match in ENTRY.finditer(text):
        field = match.group("field")
        raw_id = match.group("id")
        food_id = (
            raw_id.strip('"') if raw_id.startswith('"') else resolve_config_id(raw_id)
        )
        calories = resolve_calories(match.group("calories"), resolved)
        resolved[field] = calories
        rows.append((food_id, calories))

    if not rows:
        raise SystemExit("found no FoodInfo entries - has the table been restructured?")

    seen: dict[str, float] = {}
    for food_id, calories in rows:
        if food_id in seen and seen[food_id] != calories:
            raise SystemExit(f"{food_id} appears twice with different calories")
        seen[food_id] = calories

    # Plain digits: `{:g}` renders 2600000 as 2.6e+06, which is valid
    # TypeScript and unreadable in a column of round numbers.
    def number(value: float) -> str:
        return str(int(value)) if value == int(value) else repr(value)

    body = "".join(f"  {food_id}: {number(calories)},\n" for food_id, calories in rows)
    OUT.write_text(HEADER + body + FOOTER, encoding="utf-8")

    zero = [food_id for food_id, calories in rows if calories == 0]
    print(f"wrote {len(rows)} foods to {OUT}")
    if zero:
        # The game hides these itself - FoodInfo.Display is `CaloriesPerUnit != 0`.
        print(f"  {len(zero)} have no calories: {', '.join(zero)}")


if __name__ == "__main__":
    main()
